### ISSUE TITLE
[Issue] Under Sd.WebUI, it's not installing properly

### ISSUE THREAD

**Issue by CasualDev242** [vladmandic/sd-extension-chainner#8]
I get the following error in my log:

```
*** Error loading script: chainner_model.py
    Traceback (most recent call last):
      File "D:\sd.webui\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd.webui\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd.webui\webui\extensions\sd-extension-chainner\scripts\chainner_model.py", line 10, in <module>
        from modules.shared import opts, log, paths, readfile, OptionInfo # pylint: disable=wrong-import-order
    ImportError: cannot import name 'log' from 'modules.shared' (D:\sd.webui\webui\modules\shared.py)
```

**Comment by vladmandic** [comment]
this extension is intended for sdnext only and there its pre-installed.
